[package]
name = "aoc"
version = "0.1.0"
authors = ["nemo <nemo@redbrick.dcu.ie>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9"
regex = "1"
